# Site settings
title: "Karthik portfolio"
description: "karthik portfolio."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Karthik Vechalapu"
resume_title:                   "Lead Frontend Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "vkarthik.durga@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "575-639-1560"
resume_contact_address:         "Austin TX, 78641"

resume_header_contact_info:     "Austin TX, 78641 • 575-639-1560 • vkarthik.durga@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Results-oriented Senior Frontend Developer with 10+ years of hands-on experience crafting cutting-edge web applications. Proficient in HTML5, CSS3, JavaScript, Typescript, JQuery, Drupal, PHP, AngularJS, Ajax & Docker. I bring a robust skill set in responsive design, performance optimization, and user-centric development. Collaborative and adaptable, I excel in translating business objectives into polished, efficient, and visually striking interfaces. Proven ability to lead and mentor teams, ensuring the successful delivery of high-impact projects. Eager to contribute my expertise to drive frontend excellence in a dynamic and innovative environment.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://venkatav5a8.github.io/resume/"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/karthik-vechalapu-715067121/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
